### PR TITLE
config fixes

### LINKED ISSUE #853: Crash when too many MIDI "devices" present
Maybe related to `MAX_MIDI_PLAYER_MENU_ITEMS` being fixed at 16 but the soundfont list is allowed to grow indefinitely? Notice OPL3 is missing at the end and is replaced with a generic "midi player" name.

https://user-images.githubusercontent.com/56656010/209482575-562b2cab-1bed-4d5f-9bd7-cc907b97bcda.mp4

### PR DESCRIPTION
**Pull request by rfomin**
Fix #853 

Also fix [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1050-dec-21-2022-updated-winmbf/?do=findComment&comment=2587260)

### CODE REVIEW

File: src/m_misc.c [hunk 1]
```diff
@@ -2749,7 +2749,7 @@ boolean M_ParseOption(const char *p, boolean wad)
   //jff 3/3/98 skip lines not starting with an alphanum
   // killough 10/98: move to be made part of main test, add comment-handling
 
-  if (sscanf(p, "%79s %99[^\n]", name, strparm) != 2 || !isalnum(*name) ||
+  if (sscanf(p, "%79s %255[^\n]", name, strparm) != 2 || !isalnum(*name) ||
```
Comment (rfomin) [inline src/m_misc.c:2752]: @fabiangreffrath I'm tired of this code, also `256` is not enough for a path in modern OSes. What if we rewrite the config parser using `u_scanner` (not in this PR)?

**Review by fabiangreffrath — APPROVED** [review]

File: src/m_misc.c (hunk 1 above)
Comment (fabiangreffrath) [reply src/m_misc.c:2752]: Sure, the config code is archaic. Remember when it used ints to store char pointers? 

I agree we should use the opportunity after the next point release (due this week) to clean up the config system and menu a bit.
