### PR TITLE
fix saving texture offsets

### LINKED ISSUE #2313: Boom scroll tagged wall wrt 1st side sector (action 249) position not saved in savegames properly
Here's a wad that uses the boom action 249 (Scroll Tagged Wall w.r.t. 1st Side's Sector) to fake sliding doors. The height of the door is meant to control the horizontal offset of the texture, to create the appearance of sliding.

If I go through the door, save the game before the door closes and *without turning around*, load the game, and then turn around, the textures look like they are in the closed position, but the door is actually open. 

Looking at the door when saving it causes the texture to be saved properly, though the offsets on other side are sometimes incorrect.

Tested with latest git version on Linux.

[sliddoor.wad.zip](https://github.com/user-attachments/files/21224145/sliddoor.wad.zip)

### PR DESCRIPTION
**Pull request by rfomin**
Fix #2313

### CODE REVIEW

File: src/p_saveg.c [hunk 1]
```diff
@@ -2281,13 +2284,18 @@ void P_UnArchiveWorld (void)
...
 	    si->rowoffset = saveg_read32();
-	    // [crispy] smooth texture scrolling
-	    si->basetextureoffset = si->textureoffset;
-	    si->baserowoffset = si->rowoffset;
 
             si->toptexture = saveg_read16();
             si->bottomtexture = saveg_read16();
             si->midtexture = saveg_read16();
+
+            if (saveg_compat > saveg_woof1500)
```
Comment (fabiangreffrath) [inline src/p_saveg.c]: What happens to `basetextureoffset` and `baserowoffset` in the `saveg_compat <= saveg_woof1500` case?

Comment (rfomin) [reply src/p_saveg.c]: Right, we need these lines:
```c
si->basetextureoffset = si->textureoffset;
si->baserowoffset = si->rowoffset;
```
I'm not sure if this approach is correct. Perhaps we should rename `textureoffset` to `interptextureoffset` and `basetextureoffset` to `textureoffset`. Then, we would have to change some code in `r_bsp.c`, but the saves would work without changes.

Comment (fabiangreffrath) [reply src/p_saveg.c]: Sure, I'm all for simple solutions!

Comment (rfomin) [reply src/p_saveg.c]: From my testing, it works, but it looks a little scary. All of the renaming was done with clang tools.
