### PR TITLE
fix next weapon key with `doom_weapon_toggles == 0`

### LINKED ISSUE #1779: Previous/next-weapon button issues
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9802804920)._

With `doom_weapon_toggles` disabled, the next-weapon button stops working once the Fist or Shotgun are selected (either as pending or ready weapon). The previous-weapon button doesn't get stuck, but it skips the Chainsaw and SSG altogether.

With `doom_weapon_toggles` enabled, the next-weapon button skips the Fist (even with Berserk) and Shotgun. Also, the non-Berserk Fist is skipped by both buttons even in non-vanilla complevels where it _can_ be switched to manually through its dedicated button, although this could be intentional.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1779

### CODE REVIEW

File: src/g_game.c [hunk 1]
```diff
@@ -219,20 +219,16 @@ int    bodyqueslot, bodyquesize, default_bodyquesize; // killough 2/8/98, 10/98
...
-    { wp_fist,            wp_fist },
-    { wp_chainsaw,        wp_fist },
-    { wp_pistol,          wp_pistol },
-    { wp_shotgun,         wp_shotgun },
-    { wp_supershotgun,    wp_shotgun },
-    { wp_chaingun,        wp_chaingun },
-    { wp_missile,         wp_missile },
-    { wp_plasma,          wp_plasma },
-    { wp_bfg,             wp_bfg }
+static const weapontype_t weapon_order_table[] = {
```
Comment (fabiangreffrath) [inline src/g_game.c:222]: Now this always allows to switch from chainsaw back to fists, right? I think this was the reason for the two-fold table.

Comment (rfomin) [reply src/g_game.c:222]: No, if the player has a chainsaw, it will only switch to firsts with berserk. See
https://github.com/fabiangreffrath/woof/blob/ff6c43e238087fdc455efde074c877a19ab2fa6d/src/g_game.c#L737

Comment (fabiangreffrath) [reply src/g_game.c:222]: Ah, right, this check comes later, so we don't need it in the prev/next table. Thanks!

**Review by fabiangreffrath — APPROVED** [review]

File: src/g_game.c (hunk 1 above)
Comment (rfomin) [reply src/g_game.c:222]: Still not sure if it works properly. @MrAlaux could you please check?

Comment (MrAlaux) [reply src/g_game.c:222]: > Still not sure if it works properly. @MrAlaux could you please check?

`doom_weapon_toggles == 0` works properly now: both buttons can switch to all weapons, except the non-Berserk Fist

As for `doom_weapon_toggles == 1`, or vanilla complevel (in which case `doom_weapon_toggles` should take no effect):
\- _Previous_ can switch to all weapons, except the non-Berserk Fist
\- _Next_ omits the Fist (regardless of Berserk) and Shotgun

Comment (rfomin) [reply src/g_game.c:222]: I have disabled `doom_weapon_toggles` for the next weapon here: https://github.com/fabiangreffrath/woof/pull/1785/commits/3ac46d970360b7784c6d3d86895021e99df47b7f What do you think?

Comment (MrAlaux) [reply src/g_game.c:222]: Sure enough, the prev/next-weapon buttons seem to completely ignore `doom_weapon_toggles` now, and both can switch to all weapons (except, as you may guess, the non-Berserk Fist). I think this works best.

FWIW, vanilla complevel remains unaffected.

It should be obvious, but I should have clarified that the Fist and Shotgun are only skipped when you have the Chainsaw and SSG respectively.
