### PR TITLE
fix -dogs default value, add error message

### LINKED ISSUE #908: How to get helper dogs?
-dogs from mbf doesn't work.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #908

### CODE REVIEW

File: src/g_game.c [hunk 1]
```diff
@@ -2802,7 +2802,7 @@ static int G_GetHelpers(void)
     //
 
     j = M_CheckParm ("-dogs");
-  return j ? j+1 < myargc ? M_ParmArgToInt(j) : 1 : default_dogs;
+  return j ? (j+1 < myargc && myargv[j+1][0] != '-') ? M_ParmArgToInt(j) : 1 : default_dogs;
```
Comment (fabiangreffrath) [inline src/g_game.c:2805]: If we replace `default_dogs` with `(demo_version < 203 ? 0 : default_dogs)` here, we can check for `dogs` in the condition below (L 3116) and don't have to check for both command line parameters again.

Comment (rfomin) [reply src/g_game.c:2805]: But `demo_version` is not set when calling `G_GetHelpers()`.

Comment (fabiangreffrath) [reply src/g_game.c:2805]: Ah, right!

**Review by fabiangreffrath — APPROVED** [review]
