### PR TITLE
remove VX_NearbySprites

### LINKED ISSUE #1700: Crash in `R_NearbySprites` with voxels
It's rare with the regular build, but with ASAN enabled I always get it at random places while playing demo1 from doom.wad. Command line:
```
woof -iwad doom.wad -file VoxelDoom_v_2.3.pk3 -playdemo demo1
```
ASAN report:
<details>

```
=================================================================
==10788==ERROR: AddressSanitizer: heap-use-after-free on address 0x117254fae198 at pc 0x7ffa15b9fbd5 bp 0x0042ca4fee60 sp 0x0042ca4fee68
READ of size 8 at 0x117254fae198 thread T0
    #0 0x7ffa15b9fbd4 in R_NearbySprites C:\develop\woof\src\r_things.c:768
    #1 0x7ffa15b91539 in R_RenderPlayerView C:\develop\woof\src\r_main.c:940
    #2 0x7ffa15a1fabd in D_Display C:\develop\woof\src\d_main.c:361
    #3 0x7ffa15a26fe4 in D_DoomMain C:\develop\woof\src\d_main.c:2743
    #4 0x7ffa15a64ded in Woof_Main C:\develop\woof\src\i_main.c:70
    #5 0x7ff6d38d283c in SDL_main C:\develop\woof\win32\win_launcher.c:36
    #6 0x7ff6d38d9eda in main_getcmdline C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:80
    #7 0x7ff6d38d9f82 in main C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:94
    #8 0x7ff6d38d3e58 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #9 0x7ff6d38d3d3d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #10 0x7ff6d38d3bfd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #11 0x7ff6d38d3eed in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #12 0x7ffa3cdc7343 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #13 0x7ffa3d2626b0 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

0x117254fae198 is located 152 bytes inside of 368-byte region [0x117254fae100,0x117254fae270)
freed by thread T0 here:
    #0 0x7ffa09212548 in free D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:230
    #1 0x7ffa15be04c7 in Z_Free C:\develop\woof\src\z_zone.c:119
    #2 0x7ffa15b79bc3 in P_RemoveThinkerDelayed C:\develop\woof\src\p_tick.c:155
    #3 0x7ffa15b7a7fa in P_RunThinkers C:\develop\woof\src\p_tick.c:240
    #4 0x7ffa15b7922f in P_Ticker C:\develop\woof\src\p_tick.c:314
    #5 0x7ffa15a3371e in G_Ticker C:\develop\woof\src\g_game.c:2924
    #6 0x7ffa15a275a9 in RunTic C:\develop\woof\src\d_net.c:91
    #7 0x7ffa15a1c930 in TryRunTics C:\develop\woof\src\d_loop.c:878
    #8 0x7ffa15a26fd6 in D_DoomMain C:\develop\woof\src\d_main.c:2739
    #9 0x7ffa15a64ded in Woof_Main C:\develop\woof\src\i_main.c:70
    #10 0x7ff6d38d283c in SDL_main C:\develop\woof\win32\win_launcher.c:36
    #11 0x7ff6d38d9eda in main_getcmdline C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:80
    #12 0x7ff6d38d9f82 in main C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:94
    #13 0x7ff6d38d3e58 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #14 0x7ff6d38d3d3d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #15 0x7ff6d38d3bfd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #16 0x7ff6d38d3eed in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16
    #17 0x7ffa3cdc7343 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017343)
    #18 0x7ffa3d2626b0 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x1800526b0)

previously allocated by thread T0 here:
    #0 0x7ffa09212688 in malloc D:\a\_work\1\s\src\vctools\asan\llvm\compiler-rt\lib\asan\asan_malloc_win.cpp:252
    #1 0x7ffa15bdfe01 in Z_Malloc C:\develop\woof\src\z_zone.c:66
    #2 0x7ffa15b2ff3a in P_SpawnMobj C:\develop\woof\src\p_mobj.c:822
    #3 0x7ffa15b14692 in P_KillMobj C:\develop\woof\src\p_inter.c:790
    #4 0x7ffa15b1108b in P_DamageMobjBy C:\develop\woof\src\p_inter.c:935
    #5 0x7ffa15b25cda in PTR_ShootTraverse C:\develop\woof\src\p_map.c:1659
    #6 0x7ffa15b2ddbe in P_TraverseIntercepts C:\develop\woof\src\p_maputl.c:698
    #7 0x7ffa15b2c279 in P_PathTraverse C:\develop\woof\src\p_maputl.c:951
    #8 0x7ffa15b1afc4 in P_LineAttack C:\develop\woof\src\p_map.c:1730
    #9 0x7ffa15b48c27 in P_GunShot C:\develop\woof\src\p_pspr.c:921
    #10 0x7ffa15b42509 in A_FireShotgun C:\develop\woof\src\p_pspr.c:960
    #11 0x7ffa15b4053b in P_SetPspritePtr C:\develop\woof\src\p_pspr.c:134
    #12 0x7ffa15b4743f in P_SetPsprite C:\develop\woof\src\p_pspr.c:92
    #13 0x7ffa15b3f2d0 in P_MovePsprites C:\develop\woof\src\p_pspr.c:1121
    #14 0x7ffa15b7bdbd in P_PlayerThink C:\develop\woof\src\p_user.c:540
    #15 0x7ffa15b79225 in P_Ticker C:\develop\woof\src\p_tick.c:311
    #16 0x7ffa15a3371e in G_Ticker C:\develop\woof\src\g_game.c:2924
    #17 0x7ffa15a275a9 in RunTic C:\develop\woof\src\d_net.c:91
    #18 0x7ffa15a1c930 in TryRunTics C:\develop\woof\src\d_loop.c:878
    #19 0x7ffa15a26fd6 in D_DoomMain C:\develop\woof\src\d_main.c:2739
    #20 0x7ffa15a64ded in Woof_Main C:\develop\woof\src\i_main.c:70
    #21 0x7ff6d38d283c in SDL_main C:\develop\woof\win32\win_launcher.c:36
    #22 0x7ff6d38d9eda in main_getcmdline C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:80
    #23 0x7ff6d38d9f82 in main C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.1-ba01639f2d.clean\src\main\windows\SDL_windows_main.c:94
    #24 0x7ff6d38d3e58 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #25 0x7ff6d38d3d3d in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #26 0x7ff6d38d3bfd in __scrt_common_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #27 0x7ff6d38d3eed in mainCRTStartup D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:16

SUMMARY: AddressSanitizer: heap-use-after-free C:\develop\woof\src\r_things.c:768 in R_NearbySprites
Shadow bytes around the buggy address:
  0x037a9f875be0: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x037a9f875bf0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x037a9f875c00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x037a9f875c10: fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa
  0x037a9f875c20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x037a9f875c30: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
  0x037a9f875c40: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x037a9f875c50: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x037a9f875c60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x037a9f875c70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x037a9f875c80: fd fd fd fd fd fd fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10788==ABORTING
```
</details>

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1700 

This fixes crashes and using [DrawTest.zip](https://github.com/fabiangreffrath/woof/files/14412889/DrawTest.zip) voxels do not disappear. I wonder which method is more effective.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, this does another BSP walk. I think this is because it was developed for Vanilla/Chocolate which don't have the `sec_t->touching_thinglist` concept.

File: src/r_voxel.c [hunk 1]
```diff
@@ -1069,57 +1069,3 @@ void VX_DrawVoxel (vissprite_t * spr)
 
 	VX_RecursiveDraw (spr, 0, 0, v->x_size, v->y_size);
 }
-
-//------------------------------------------------------------------------
-
-static boolean VX_CheckBBox (fixed_t * bspcoord)
-{
-	if (bspcoord[BOXRIGHT]  <= viewx - VX_NEAR_RADIUS) return false;
```
Comment (fabiangreffrath) [inline src/r_voxel.c:1077]: We don't need `VX_NEAR_RADIUS` anymore.

**Review by fabiangreffrath — APPROVED** [review]
