### PR TITLE
calculate mouse position relative to logical presentation rect

### LINKED ISSUE #2499: Mouse menu navigation "hitboxes" are misaligned
Latest master. Steps to reproduce: Set widescreen to various values and test. Toggle fullscreen and test again.

https://github.com/user-attachments/assets/8fbb198c-e75f-496b-8c1b-3c415c7ffbac

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #2499

### CODE REVIEW

File: src/i_video.c [hunk 1]
```diff
@@ -594,14 +591,11 @@ static void UpdateMouseMenu(void)
...
-    SDL_GetRenderScale(renderer, &scalex, &scaley);
+    x = (int)((outx - rect.x) * video.unscaledw / rect.w);
+    y = (int)((outy - rect.y) * SCREENHEIGHT / rect.h);
 
-    int deltax = rect.x * scalex;
-    int deltay = rect.y * scaley;
-
-    x = (x - deltax) * video.unscaledw / (w - deltax * 2);
-    y = (y - deltay) * SCREENHEIGHT / (h - deltay * 2);
+    x = CLAMP(x, 0, video.unscaledw);
```
Comment (fabiangreffrath) [inline src/i_video.c]: Not sure where's the best place to clamp?

File: src/i_video.c [hunk 2]
```diff
@@ -594,15 +588,14 @@ static void UpdateMouseMenu(void)
...
+    outy = clampf((outy - rect.y) / rect.h, 0.0f, 1.0f);
 
-    int deltax = rect.x * scalex;
-    int deltay = rect.y * scaley;
-
-    x = (x - deltax) * video.unscaledw / (w - deltax * 2);
-    y = (y - deltay) * SCREENHEIGHT / (h - deltay * 2);
+    int x, y;
+    x = (int)(outx * video.unscaledw);
+    y = (int)(outy * SCREENHEIGHT);
```
Comment (ceski-1) [inline src/i_video.c]: Can simplify further:
```c
int x = ...
int y = ...
```

**Review by rfomin — APPROVED** [review]
LGTM.
