### PR TITLE
Fix `-deh` parameter load order

### LINKED ISSUE #2370: Autoloaded DEHs are loaded after `-deh`
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/17020712262)._

E.g. if I run `woof.exe -deh IndC.deh` while having `D2DEHFIX.DEH` in `autoload/doom2-all/`, the latter patch is loaded after the former, contrary to what is done with WADs. Same issue with `.bex`.

### PR DESCRIPTION
**Pull request by elf-alchemist**
Fixes #2370

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thank you! Does this mean we can move `chex.deh` back to its own autoload directory?

**Comment by fabiangreffrath** [comment]
This looks correct to me. What is DSDA's load order, actually?

File: src/d_main.c [hunk 1]
```diff
@@ -2075,46 +2075,52 @@ void D_DoomMain(void)
...
   // Avoid loading DEHACKED lumps embedded into WAD files.
   //
-
   if (!M_ParmExists("-nodeh"))
   {
     W_ProcessInWads("DEHACKED", DEH_LoadLump, PROCESS_IWAD);
   }
-
-  // process deh in wads and .deh files from autoload directory
-  // before deh in wads from -file parameter
```
Comment (fabiangreffrath) [inline src/d_main.c:2104]: So we load .deh files from autoload directories even if the `-nodeh` parameter is given?

Comment (elf-alchemist) [reply src/d_main.c:2104]: Yes that is intentional, `-nodeh` is meant to operate on WADs specifically, and matches the current DSDA behavior, as well. Clarified in f05d1caa1687f31fb056923b0355717cdecfc064

**Comment by elf-alchemist** [comment]
> I'd even say it deserves another line explaining that this prefers DSDA-Doom's load order over Chocolate Doom's load order, which would load 6 between 3 and 4.

Expanded upon in f05d1caa1687f31fb056923b0355717cdecfc064

**Comment by fabiangreffrath** [comment]
Thank you! May I adjust the wording a bit?

**Review by fabiangreffrath — APPROVED** [review]
Thank you!

**Review by fabiangreffrath — APPROVED** [review]
Now it fits, sorry for the trouble.

**Comment by rfomin** [comment]
> @rfomin Any idea why "Linux GCC" CI keeps failing?

Ubuntu 22.04 appears to have an old version of GCC without C++20 support, meaning there is no built-in `std::format` library. Therefore, we must either switch to a newer version of Ubuntu, or patch OpenAL to use the `fmt` library, or install a newer version of GCC/Clang on Ubuntu 22.04. We use an older version of Ubuntu on our CI to support Linux distributions with older versions of glibc.

**Comment by fabiangreffrath** [comment]
> patch OpenAL to use the `fmt` library

Or rather unpatch it to use the embedded library?

https://github.com/microsoft/vcpkg/blob/647ed7e95d44a7f1da17cd9eff950de7bbaed64f/ports/openal-soft/devendor-fmt.diff

**Comment by rfomin** [comment]
> Or rather unpatch it to use the embedded library?

They removed the vendored library because OpenAL switched to C++20. I think we have to use the `fmt::` namespace instead of `std::`.

> > We use an older version of Ubuntu on our CI to support Linux distributions with older versions of glibc.
> 
> Was there a bug report about it? If not, I'd suggest to just switch to `ubuntu-latest`.

Yes, I think there was a bug report in 2024. I don't know what the current situation is with the usage of Linux distributions. I guess it's safe to switch to Ubuntu 24 (`ubuntu-latest`) at this point.
