### PR TITLE
fix solid bg HOM

### LINKED ISSUE #1624: HOM in Automap with solid background
_Tested in the [almost-latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8428043530)._

See for yourself, on top of the Status Bar:
woof0001

My native resolution (the one shown in the screenshot) is the only one with which I could get the HOM to manifest. Of course, I couldn't try higher resolutions.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1624 

> The right side of the status bar has a HOM going from 3200x2400 to 3440x1440.

@ceski-1 I can't reproduce it (or maybe I can't see it). Is it fixed for you?

### CODE REVIEW

**Comment by ceski-1** [comment]
> @ceski-1 I can't reproduce it (or maybe I can't see it). Is it fixed for you?

If I run the HOM test code before this PR, a HOM line appears above the status bar with the automap active for various resolutions, just like Alaux's screenshot. If I apply the changes from this PR and run the HOM test again, the HOM line does not appear. Note that the HOM test code doesn't actually catch the HOM lines in `I_CheckHOM()` but if you watch the screen, you'll see them.

**Comment by rfomin** [comment]
> If I run the HOM test code before this PR, a HOM line appears above the status bar with the automap active for various resolutions, just like Alaux's screenshot. If I apply the changes from this PR and run the HOM test again, the HOM line does not appear.

Right, this PR fixes that. It also fixes the right side of the "game window" with screenblocks < 10 on 3440x1440 for example.

Sorry I was not clear, I was talking about the right side of the status bar, which we discuss from this comment: https://github.com/fabiangreffrath/woof/pull/1525#issuecomment-1958035286 I am no longer able to reproduce it.

**Comment by ceski-1** [comment]
> Sorry I was not clear, I was talking about the right side of the status bar, which we discuss from this comment: [#1525 (comment)](https://github.com/fabiangreffrath/woof/pull/1525#issuecomment-1958035286) I am no longer able to reproduce it.

No, it doesn't fix that problem: [pic](https://github.com/fabiangreffrath/woof/assets/56656010/f21cea17-0e90-40fe-bf12-63642f374d20)

**Comment by rfomin** [comment]
> No, it doesn't fix that problem: [pic](https://github.com/fabiangreffrath/woof/assets/56656010/f21cea17-0e90-40fe-bf12-63642f374d20)

There's a black column on the right side of the status bar? I can't get it: [pic](https://github.com/fabiangreffrath/woof/assets/5077629/e579fabf-b618-4c7b-8229-b452e11ded39) I have merged "master" and "solid_bg_hom" into "video_test".

**Comment by ceski-1** [comment]
> I have merged "master" and "solid_bg_hom" into "video_test".

Yes, I did the same. Clean config with `dynamic_resolution 0`. Command line: `woof -devparm -test -verbose -warp 1`. Patch: 
[homtest_solidbghom.patch](https://github.com/fabiangreffrath/woof/files/14783202/homtest_solidbghom.patch) Only difference is I made the HOM lines red, cut the other resolutions out, and made the delay 3 seconds instead of 3 tics.

**Comment by rfomin** [comment]
I still can't reproduce this. I've updated the [HOM test](https://github.com/fabiangreffrath/woof/pull/1525) branch, I'm only testing at 3440x1440 resolution and with the FOV test disabled.

Is the black column on the side of the status bar then filled with garbage pixels?

**Comment by ceski-1** [comment]
> I'm only testing at 3440x1440 resolution and with the FOV test disabled.

It's just the transition from 3200x2400 to 3440x1440 for me. So launching directly into 3440x1440 is fine. Maybe it's not important.

Status bar is fine:

```c
static struct {
    int w, h;
} native_res[] = {
    { 3440, 1440 },
    { 5120, 2160 }
};
```

Black columns on the right side of status bar:

```c
static struct {
    int w, h;
} native_res[] = {
    { 3200, 2400 },
    { 3440, 1440 },
    { 5120, 2160 }
};
```

**Comment by rfomin** [comment]
> It's just the transition from 3200x2400 to 3440x1440 for me.

This fixed it for me: https://github.com/fabiangreffrath/woof/pull/1626/commits/323f5bbb3beb58c654cb2dcaee6f4173fd5a8518 I think that micro-optimisation is not important.

**Comment by ceski-1** [comment]
> This fixed it for me: [323f5bb](https://github.com/fabiangreffrath/woof/commit/323f5bbb3beb58c654cb2dcaee6f4173fd5a8518) I think that micro-optimisation is not important.

Yes, that fixes it for me too.

File: src/st_stuff.c [hunk 1]
```diff
@@ -441,24 +441,7 @@ void ST_refreshBackground(boolean force)
 
     // [crispy] copy entire video.unscaledw, to preserve the pattern to the left
     // and right of the status bar in widescren mode
-    if (!force)
```
Comment (fabiangreffrath) [inline src/st_stuff.c:444]: I don't even remember why this branch was here?

Comment (rfomin) [reply src/st_stuff.c:444]: There is another `V_CopyRect` in `ST_drawWidgets`, so it's not necessary to copy the ST_BAR itself in case of `R_ExecuteSetViewSize`. I don't think we need this complication.
