### PR TITLE
fix next/prev weapon without carousel

### LINKED ISSUE #2196: Next/prev weapon doesn't work with carousel disabled
Issue started with this commit: https://github.com/fabiangreffrath/woof/commit/e0ebe4237c8340f865dad016e4b13950bc85de2e

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #2196

### CODE REVIEW

**Comment by ceski-1** [comment]
I'm not really familiar with g_nextweapon.c, so I'll ask some questions and share some results.

What is the traditional behavior for next/prev weapon when the automap is open? What is the desired behavior? What takes priority when the automap is open? Should the behavior differ for the overlay automap (because the weapons are visible)?

With this PR, here's how next/prev weapon behaves with the automap open:
- Keyboard Q/E keys: weapons cycle, no automap zooming
- Mouse4/Mouse5 buttons (side buttons): weapons cycle, no automap zooming
- Mousewheel up/down: automap zooms in/out, no weapon cycling
- Gamepad LB/RB buttons: weapons cycle, no automap zooming

**Comment by fabiangreffrath** [comment]
> What is the traditional behavior for next/prev weapon when the automap is open? 

Traditional ports, including MBF, did not have prev/next weapon bindings. Chocolate Doom allows to bind prev/next weapon to the mouse wheel, but does not allow to bind Automap zoom to any mouse button, so the events are passed through if the Automap is open.

> What takes priority when the automap is open? 

I think the Automap bindings should be given priority when the Automap is open.

> Should the behavior differ for the overlay automap (because the weapons are visible)?

This would be surprising IMHO.

> With this PR, here's how next/prev weapon behaves with the automap open:
> 
>     * Keyboard Q/E keys: weapons cycle, no automap zooming
> 
>     * Mouse4/Mouse5 buttons (side buttons): weapons cycle, no automap zooming
> 
>     * Mousewheel up/down: automap zooms in/out, no weapon cycling
> 
>     * Gamepad LB/RB buttons: weapons cycle, no automap zooming

Sounds reasonable to me (I assume Q/E and mouse side buttons are bound to prev/next weapon).

File: src/g_nextweapon.c [hunk 1]
```diff
@@ -138,12 +138,12 @@ typedef enum
 {
     nw_state_none,
     nw_state_activate,
-    nw_state_currently_active,
     nw_state_deactivate,
     nw_state_cmd
 } next_weapon_state_t;
 
 static next_weapon_state_t state;
+static boolean currently_active;
```
Comment (ceski-1) [inline src/g_nextweapon.c:146]: Should this be reset to `false` in `G_NextWeaponReset`?

**Review by ceski-1 — APPROVED** [review]

File: src/g_nextweapon.c (hunk 1 above)
Comment (fabiangreffrath) [reply src/g_nextweapon.c:146]: Most probably yes!
