### PR TITLE
remove ASM div64_32() implementation

### LINKED ISSUE #2219: Voxels crash in Linux
A fellow user of EndeavourOS (`6.13.5-arch1-1` according to `uname -r`) reported that voxels crashed Nugget with a `Floating point exception` after starting a new game and running around for a few seconds, so I asked them to try various builds and we concluded that the issue is in Woof.

The crash began with [this AppImage](https://github.com/fabiangreffrath/woof/actions/runs/12213228205) (between the 15.0.1 and 15.1.0 releases), persisting all the way to [the latest](https://github.com/fabiangreffrath/woof/actions/runs/13616956442).

It's worth noting that they allegedly also tried an AUR package of 15.2.0, and it didn't crash.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
* Prone to miscompilation
* Only helps with very old PCs
* Really only helps with voxel rendering

Fixes #2219

### CODE REVIEW

File: src/m_fixed.h [hunk 1]
```diff
@@ -38,8 +38,8 @@
       {
           return a / b;
       }
-      int32_t lo = a;
-      int32_t hi = a >> 32;
+      volatile int32_t lo = a;
```
Comment (rfomin) [inline src/m_fixed.h:41]: How about `int32_t lo = (int32_t) a;`?
It seems to be another case of UB that will differ in various versions of compilers.

**Comment by MrAlaux** [comment]
The original reporter tried this and said that it fixed the crash.

File: src/m_fixed.h (hunk 1 above)
Comment (fabiangreffrath) [reply src/m_fixed.h:41]: Tried this, same crash.

```patch
--- a/src/m_fixed.h
+++ b/src/m_fixed.h
@@ -38,8 +38,14 @@
       {
           return a / b;
       }
-      int32_t lo = a;
-      int32_t hi = a >> 32;
+      union {
+          int64_t v64;
+          int32_t v32[2];
+      } d = {a};
+
+      int32_t lo = d.v32[0];
+      int32_t hi = d.v32[1];
+
       asm("idivl %[divisor]" : "+a" (lo), "+d" (hi) : [divisor] "r" (b));
       return lo;
   }
```

Comment (fabiangreffrath) [reply src/m_fixed.h:41]: > How about `int32_t lo = (int32_t) a;`?

Same crash.

Comment (fabiangreffrath) [reply src/m_fixed.h:41]: I think the problem is that `a` and `b` are both input and output variables to the `asm()` call. However, the issue is very compiler specific. Ubuntu-latest uses gcc-11.2 and I cannot reproduce it with gcc-14.2 on my main system with the exact same build flags. Also, it is optimization specific and won't occur with gcc-11.2 in a debug build with `-O0`.

Comment (fabiangreffrath) [reply src/m_fixed.h:41]: Reminds me of this bug, where we also never really understood what was going on:

https://github.com/fabiangreffrath/woof/commit/3c526e70688b18f65568ef3b3ee235fd3a9c2c13

Comment (rfomin) [reply src/m_fixed.h:41]: This was a miscompilation with Clang -O3. May be fixed in newer versions of the compiler.

Comment (fabiangreffrath) [reply src/m_fixed.h:41]: Yes, it's possible the same thing happens here with gcc-11.

Comment (rfomin) [reply src/m_fixed.h:41]: Anyway, I suggest to remove the GCC version of `div64_32`. It helps only for old CPUs and is only noticeable with voxels (we have very few `FixedDiv` in other code).

**Review by rfomin — APPROVED** [review]
