### PR TITLE
fix crash at REJECT load from WAD in zip

### LINKED ISSUE #2501: Crash when starting new game in PUSS IV
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/19822795327)._

Attempting to start a new game in [PUSS IV](https://www.doomworld.com/idgames/themes/xmas/12days-v4) makes the game crash.

First reported in Nugget: https://github.com/MrAlaux/Nugget-Doom/issues/162.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #2501

### CODE REVIEW

File: src/p_setup.c [hunk 1]
```diff
@@ -1655,7 +1655,7 @@ static boolean P_LoadReject(int lumpnum, int totallines)
     // Otherwise, we need to allocate a buffer of the correct size
     // and pad it with appropriate data.
 
-    lumplen = W_LumpLengthWithName(lumpnum, "REJECT");
+    lumplen = W_LumpLength(lumpnum);
```
Comment (rfomin) [inline src/p_setup.c]: @fabiangreffrath Why is `W_LumpLengthWithName` needed here?

[PUSS IV](https://www.doomworld.com/idgames/themes/xmas/12days-v4) has empty REJECT lumps with a size of 13 in the lump header table. It crashes during the `memcpy` from the WAD in memory because `W_LumpLengthWithName` returns 0.

Comment (rfomin) [reply src/p_setup.c]: Wait, [PUSS IV](https://www.doomworld.com/idgames/themes/xmas/12days-v4) has CWILV00 patch in the middle of MAP01:
image

It still works with DSDA-Doom and with unzipped WADs in Woof. Oh well.

Comment (fabiangreffrath) [reply src/p_setup.c]: I guess the REJECT matric is read from the CWILV00 lump in that case.

Comment (rfomin) [reply src/p_setup.c]: I propose this solution: https://github.com/fabiangreffrath/woof/pull/2502/commits/3424be0e17fe40711876693650ad8be9c6c54ef0

File: src/p_setup.c [hunk 2]
```diff
@@ -1667,7 +1667,7 @@ static boolean P_LoadReject(int lumpnum, int totallines)
         unsigned int padvalue;
 
         rejectmatrix = Z_Malloc(minlength, PU_LEVEL, (void **) &rejectmatrix);
-        W_ReadLump(lumpnum, rejectmatrix);
+        W_ReadLumpSize(lumpnum, rejectmatrix, minlength);
```
Comment (fabiangreffrath) [inline src/p_setup.c:1670]: We have the same code in `src/p_udmf.c`.

Comment (rfomin) [reply src/p_setup.c:1670]: Done in https://github.com/fabiangreffrath/woof/pull/2502/commits/9f847e88cb1b81ff6328d193e95c3f052a149f59
