### PR TITLE
fix ESC reset with mini-thermo items affects multi-choice select items

### LINKED ISSUE #1153: Thermo-type menu items bug
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/5583651442)._

Best I can describe the bug is the thermo-type item's value text being applied to a choice-type item... somehow.

**Steps to reproduce:**

- Launch Woof, with no .cfg file present
- Go to Options > General > Page 2
- Change "Sound Module" to "OpenAL 3D" so the thermos can be interacted with
- Select "Air Absorption", set its value to 7 then deselect it by pressing Escape
- Select "Resampler" then deselect it, also by pressing Escape

The Resampler choice text should magically change from "Linear" to "Nearest". This may seem relatively harmless, but I've played around with the bug and I somehow made some Gamma Correction item text ("2.8" I think) be applied to the Resampler item without even interacting with said Gamma Correction item, and I've also triggered a crash.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1153

### CODE REVIEW

File: src/m_menu.c [hunk 1]
```diff
@@ -5945,7 +5945,7 @@ boolean M_Responder (event_t* ev)
 	    {
 	      int value = ptr1->var.def->location->i;
 
-	      if (old_value == -1)
+	      if (!(ptr1->m_flags & S_THERMO) && old_value == -1)
```
Comment (fabiangreffrath) [inline src/m_menu.c:5948]: Hm, I don't understand this change. Why do we have to special case thermometers here?

Comment (rfomin) [reply src/m_menu.c:5948]: Thermo applies the new value instantly, without confirmation. Therefore, if the user presses ESC while moving the thermo, it does not reset to the default value.

**Comment by fabiangreffrath** [comment]
Sure, thank you!
