### PR TITLE
Fix REKKR autoload directory infinite recursion

### LINKED ISSUE #2286: [Bug] Potential issue with new rekkr-all autoload dir
Woof build: [f237fb9](https://github.com/fabiangreffrath/woof/commit/f237fb9941dbee78627f04c3859a1ddeb5b4d208)
System: Win 10 x64

Issue:
I am using four files in the new rekkr-all autoload folder, i.e.
- rekbonus.wad (official bonus maps)
- rekkrwheel.wad (weapon wheel graphics)
- rekkrwide.wad (widescreen graphics)
- sbardef.lmp (part of my SBARDEF mod)

Get them here:
[rekkrtest.zip](https://github.com/user-attachments/files/20704290/rekkrtest.zip)

When all of these are inside rekkr-all, the following error message will appear when trying to boot up "Sunken Lands" (rekkrsl.wad):
**AutoLoadWADs: Failed to load
(path)\autoload\rekkr-all\rekkrwide.wad**

After removing rekkrwide.wad, the message changes to this:
**W_FILE_AddDir: Error opening
(path)\autoload\rekkr-all\sbardef.lmp**

Only after having deleted rekkrwide.wad AND rekkrwheel.wad (i.e. only with rekbonus.wad and sbardef.lmp left), the game will load. 
An additional empty autoload dir named rekkrsl.wad is created on startup.

### PR DESCRIPTION
**Pull request by elf-alchemist**
Closes #2286

### CODE REVIEW

File: src/d_main.c [hunk 1]
```diff
@@ -1493,7 +1496,10 @@ static void AutoloadPWadDir(void (*AutoLoadFunc)(const char *path))
         for (int j = 0; j < array_size(autoload_paths); ++j)
         {
             char *dir;
-            if (!strncasecmp(M_BaseName(wadfiles[i]), "rekkr", 5)) {
+            if (!strncasecmp(M_BaseName(wadfiles[i]), "rekkr.wad", 9)
+                || !strncasecmp(M_BaseName(wadfiles[i]), "rekkrs1.wad", 11)
+                || !strncasecmp(M_BaseName(wadfiles[i]), "rekkrsl.wad", 11))
+            {
```
Comment (fabiangreffrath) [inline src/d_main.c]: Please change the `GetAutoloadDir(..., true);` to `false`.

Ans please move opening brackets to the next line while at it.

**Comment by fabiangreffrath** [comment]
> Why is this necessary?

I mean, I can't test the changes right now, but I don't like how this is fixed. What is the issue that we ran into and how does hard-coding the names of three WAD file fix this?

**Comment by elf-alchemist** [comment]
> Why is this necessary?

As per the issue linked, any REKKR PWAD prefixed with `rekkr*` will bomb out at launch time with an infinite addition of the same PWADs repeatedly, if placed in the relevant autoload sub-directory.

> I mean, I can't test the changes right now, but I don't like how this is fixed. What is the issue that we ran into and how does hard-coding the names of three WAD file fix this?

While it is less clean to use hardcoded IWAD names, thankfully there are only so many for REKKR, the current named entries are all three that were supported before `rekkr-all` was introduced.


The following example uses my own autoload directory with @NightFright2k19's example PWADs:

image

File: src/d_main.c (hunk 1 above)
Comment (elf-alchemist) [reply src/d_main.c]: I changed `GetAutoloadDir(..., true)` to `false` in 67e6ecb1112d31c0c4b625089a9d0e1f997af7e8, but I'm not sure what you mean by moving the opening brackets? All relevant opening brackets are already moved to the following lines.

Comment (fabiangreffrath) [reply src/d_main.c]: Yep, right, sorry for the noise!

**Comment by fabiangreffrath** [comment]
> As per the issue linked, any REKKR PWAD prefixed with `rekkr*` will bomb out at launch time with an infinite addition of the same PWADs repeatedly, if placed in the relevant autoload sub-directory.

I see. Infinite loop because PWADs starting with `"rekkr"` load more PWADs starting with `"rekkr"`. Easy solution: please remove `rekkr-all` support for `rekkr*.wad` loaded as PWAD.

**Comment by NightFright2k19** [comment]
If it can be fixed with a simple rename of my autoload files, it would be fine for me.
