### PR TITLE
rebuild `sidescrollers` on save load

### LINKED ISSUE #732: [Bug] Signal 11 crash with "Stickney Installation"
On E1M2 of ["Stickney Installation"](https://www.doomworld.com/forum/topic/130689-stickney-installation-a-full-vanilla-doom-1-megawad/), you get a crash to desktop with the following message after strafe-running across a slime pool with some platforms:

**"I_Signalhandler: Exit on illegal storage access (Signal 11)"**

Used Woof release:
Latest Win64 workflow snapshot from "Master" branch ([3046909730](https://github.com/fabiangreffrath/woof/actions/runs/3046909730))

To reproduce:
- Load attached savegame
- Strafe-run across the slime pool ahead of you with the platforms
- Crash will eventually happen, but not every time (most reliably when trying to strafe-run right after loading the savegame)

Notes: 
- This can also happen later on if you skip this section, in any other part of the map.
- I ran the pwad with Boom compatibility as menu default, but _-complevel 2_ as startup parameter, like this:
woof.exe -iwad "../../iwad/doom.wad" -file "../../pwad/doom/stickney.wad" -complevel 2

The attached zipfile contains:
- The actual pwad (stickney.wad)
- Savegame (woofsav0.dsg)
- My config file (woof.cfg)
- Recorded demo of the incident (stickney.lmp)

[stickney_test.zip](https://github.com/fabiangreffrath/woof/files/9564664/stickney_test.zip)

### PR DESCRIPTION
**Pull request by rfomin**
Fix #732

### CODE REVIEW

File: src/p_saveg.c [hunk 1]
```diff
@@ -2693,6 +2695,7 @@ void P_UnArchiveSpecials (void)
           saveg_read_scroll_t(scroll);
           scroll->thinker.function.p1 = (actionf_p1)T_Scroll;
           P_AddThinker(&scroll->thinker);
+          P_AddSideScroller(scroll);
```
Comment (fabiangreffrath) [inline src/p_saveg.c:2698]: Only if `scroll->type == sc_side", c.f. `Add_Scroller()`.

Comment (rfomin) [reply src/p_saveg.c]: Fixed in https://github.com/fabiangreffrath/woof/pull/733/commits/c0980d55cd7a0312bda5898b3084497a633f0385
