### PR TITLE
workaround for zdbsp's incorrect sidedef removal

### LINKED ISSUE #2156: Wrong texture offsets with ZDBSP-built extended nodes
Texture offsets on the front side of a double-sided line's midtexture appear to be incorrect in maps built with ZDBSP. This only happens when the nodes are large enough that extended format gets forced - but not when extended nodes are forced from the command line on a smaller map.

I wasn't sure where to report this, but since it looks fine in ZDoom at least as far back as 2008, I'll assume that the nodes are working as intended, and are just being interpreted incorrectly by other ports (Woof, DSDA, DoomRetro).

[Attached](https://github.com/user-attachments/files/18550342/zdbsp.zip) are two wads, the only difference is that one map has less out-of-bounds geometry than the other. Both were compiled using ZDBSP 1.19 with --extended command line switch.
When played in non-GZ ports, the texture closest to the starting point gets shifted by the amount of pixels equal to the line length (?). In (G)ZDoom it appears as it should (with left side anchored in place) - though it might be because GZ disregards existing nodes and builds its own.

The attached maps also exhibit tiling issues on non-power-of-two textures. To be clear, that is not the subject of this report. The primary issue is with the 128 texture getting an offset that shouldn't be there, and said offset depending on map complexity. The root cause could be the same as with tiling though.

Image

### PR DESCRIPTION
**Pull request by elf-alchemist**
Fixes #2156

Not sure if this breaks anything else, so setting up as a draft. Tested on the broken.wad from the above issue and Eviternity II's MAP18

woof0049

woof0054

### CODE REVIEW

File: src/p_extnodes.h [hunk 1]
```diff
@@ -46,7 +47,8 @@ extern const char *const node_format_names[];
 extern mapformat_t P_CheckMapFormat(int lumpnum);
 extern nodeformat_t P_CheckDoomNodeFormat(int lumpnum);
 extern nodeformat_t P_CheckUDMFNodeFormat(int lumpnum);
-extern int P_GetOffset(struct vertex_s *v1, struct vertex_s *v2);
+extern int P_GetSidedefNum(seg_t * li, line_t * ldef);
+extern int P_GetOffset(vertex_t * v1, vertex_t * v2);
```
Comment (rfomin) [inline src/p_extnodes.h]: We use forward declarations of struct pointers to avoid including headers. This makes recompilation faster if you change the header. Please restore the old declaration `extern int P_GetOffset(struct vertex_s *v1, struct vertex_s *v2);` or remove forward declaration `struct vertex_s` on line 28. Also why change formatting (`vertex_t * v2` vs `vertex_t *v2`)?

Comment (elf-alchemist) [reply src/p_extnodes.h]: Fixed in e0b89f85371b7b31df7623642740e81eb161acec
