### PR TITLE
reset "custom skill" on enter

### LINKED ISSUE #2336: Custom skill menu shows default skill and wrong settings when leaving and returning to menu
https://github.com/user-attachments/assets/dcf816cc-6752-4db2-bad0-a8fd4cfaadef

### PR DESCRIPTION
**Pull request by rfomin**
Fix #2336

### CODE REVIEW

File: src/mn_setup.c [hunk 1]
```diff
@@ -3605,6 +3605,7 @@ void MN_CustomSkill(void)
     SetupMenu();
 
     csmenu_skill = default_skill - 1;
+    SelectSkillLevel();
```
Comment (ceski-1) [inline src/mn_setup.c:3608]: So all preferences are reset when leaving and returning to menu?

**Review by ceski-1 — APPROVED** [review]

File: src/mn_setup.c (hunk 1 above)
Comment (rfomin) [reply src/mn_setup.c:3608]: Yes, the typical scenario is that the user enters the "custom skill" menu, selects options, and starts the game.
Alternatively, we can maintain the "custom skill" state and save it to the config.

Comment (ceski-1) [reply src/mn_setup.c:3608]: > Alternatively, we can maintain the "custom skill" state and save it to the config.

This may be better. If there was the reset defaults icon in the lower right, players could use that too.

Comment (ceski-1) [reply src/mn_setup.c:3608]: Also, saving "custom skill" as the last selected default skill to the config may be a good idea too. Edit: Maybe too confusing and complicated for this idea.

Comment (rfomin) [reply src/mn_setup.c:3608]: > Edit: Maybe too confusing and complicated for this idea.

I want the "custom skill" menu to be simple and not resemble the general options menu with a reset button. For example, the Nugget/Nyan variant looks too complicated to me. However, it's a matter of personal preference. I'm not sure which approach is better.
