### PR TITLE
convert pusher source thing pointers into indices

### LINKED ISSUE #339: save/load bug in map02 AD_MORTEM.wad
WAD: [[doomworld]](https://www.doomworld.com/forum/topic/125461-ad-mortem-a-mbf21-halloween-themed-megawad-beta/)
How to reproduce: at the beginning of map02 grab the Rocket Launcher which activates Cacodemos, save the game. Loading this save crashes the port.
Same bug in DSDA-Doom 0.21.3 and the latest build of Woof.
I think it's related to Pushers. @kraflab

### PR DESCRIPTION
**Pull request by rfomin**
Fixes #339
It's probably not that simple.

### CODE REVIEW

File: Source/p_saveg.c [hunk 1]
```diff
@@ -162,6 +162,50 @@ static void saveg_writep(const void *p)
 #define saveg_read_enum saveg_read32
 #define saveg_write_enum saveg_write32
 
+// [crispy] enumerate all thinker pointers
+static int P_ThinkerToIndex(thinker_t* thinker)
```
Comment (fabiangreffrath) [inline Source/p_saveg.c:166]: Isn't this redundant with code that is already in P_ArchiveSpecials() or P_ArchiveThinkers()?

Comment (rfomin) [reply Source/p_saveg.c:166]: I think we could remove `P_ThinkerToIndex` and convert the pointer to index in `P_ArchiveSpecials`. But we still need `P_IndexToPointer`.

Comment (rfomin) [reply Source/p_saveg.c:166]: Like this:
```
if (th->function == T_Pusher)
{
  pusher_t *pusher = (pusher_t *) th;
  mobj_t *source = pusher->source;

  saveg_write8(tc_pusher);
  // convert to index
  pusher->source = i;
  saveg_write_pusher_t(pusher);
  // restore pointer
  pusher->source = source;
  continue;
}
```

Comment (fabiangreffrath) [reply Source/p_saveg.c:166]: Let's please try to integrate this into the existing savegame code as closely as possible.

Comment (rfomin) [reply Source/p_saveg.c:166]: It turns out my previous patch is not working.
To be honest, I like the current version better. The existing savegame code has separate functions for archiving thinkers and specials, so I think it would be ugly.

File: Source/p_saveg.c [hunk 2]
```diff
@@ -2638,6 +2682,8 @@ void P_UnArchiveSpecials (void)
           pusher_t *pusher = Z_Malloc (sizeof(pusher_t), PU_LEVEL, NULL);
           saveg_read_pusher_t(pusher);
           pusher->thinker.function = T_Pusher;
+          // can't convert from index to pointer, old save version
+          if (pusher->source == NULL)
```
Comment (fabiangreffrath) [inline Source/p_saveg.c:2686]: braces, please

Comment (fabiangreffrath) [reply Source/p_saveg.c:2686]: and we need a check if source is still NULL afterward and error out if pusher type is either push or pull

**Review by fabiangreffrath — CHANGES_REQUESTED** [review]

File: Source/p_saveg.c [hunk 3]
```diff
@@ -2684,7 +2684,11 @@ void P_UnArchiveSpecials (void)
           pusher->thinker.function = T_Pusher;
           // can't convert from index to pointer, old save version
           if (pusher->source == NULL)
+          {
           pusher->source = P_GetPushThing(pusher->affectee);
+            if (pusher->source == NULL)
```
Comment (fabiangreffrath) [inline Source/p_saveg.c:2689]: We need an additional check that `pusher->type == p_push`. It's perfectly fine for the other pusher types to have no source field, because they don't go through `PIT_PushThing()`, c.f. 
https://github.com/fabiangreffrath/woof/blob/4a4917c7df0445136333e5ce6e44d7fb538a7418/Source/p_spec.c#L3132

File: Source/p_saveg.c [hunk 4]
```diff
@@ -2684,7 +2684,11 @@ void P_UnArchiveSpecials (void)
...
+              I_Error("P_UnArchiveSpecials: Pusher thinker without source");
```
Comment (fabiangreffrath) [inline Source/p_saveg.c:2690]: Please add `"in sector %d", pusher->affectee`.

**Review by fabiangreffrath — CHANGES_REQUESTED** [review]

**Comment by fabiangreffrath** [comment]
Thanks! I guess we are all set now?

**Comment by rfomin** [comment]
I think yes, it works for me.
