### PR TITLE
fix crash with S_FUNC item instructions, simplify

### LINKED ISSUE #1857: Menu bug/crash
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10449481625)._

Steps to consistently cause a visual bug, with a fresh config file:

- Go to `Options > Weapons > Preferences`
- With the mouse, hover over the `Pre-Beta BFG` item
- Using the mouse wheel, switch to the `Cosmetic` tab

You should see a `( Del ) to clear` text appear on the bottom, out of nowhere.

Following similar steps in other menus can yield similar results, and even crashes. Check this out (look at the mugshot):

<details><summary>Screenshot</summary>
<p>

imagen
</p>
</details> 

If I had to guess, some pointers aren't being properly updated. Sometimes, the text on the bottom even changes all by itself periodically, without any input from my end.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1857 

I think we can implement `S_FUNC` if we need at least two of them.

ASAN report:
<details>

```
=================================================================
==8612==ERROR: AddressSanitizer: access-violation on unknown address 0xffffffffffffffff (pc 0x7ff91ebca0e2 bp 0x01b2b6380000 sp 0x00196b76f6f0 T0)
==8612==The signal is caused by a READ memory access.
    #0 0x7ff91ebca0e1 in MN_GetPixelWidth C:\develop\woof\src\mn_setup.c:3278
    #1 0x7ff91ebc759a in DrawInstructions C:\develop\woof\src\mn_setup.c:1247
    #2 0x7ff91ebc9f4e in MN_DrawWeapons C:\develop\woof\src\mn_setup.c:1545
    #3 0x7ff91ebc305f in M_Drawer C:\develop\woof\src\mn_menu.c:3102
    #4 0x7ff91eb72b82 in D_Display C:\develop\woof\src\d_main.c:432
    #5 0x7ff91eb742c7 in D_DoomMain C:\develop\woof\src\d_main.c:2734
    #6 0x7ff91eba0683 in Woof_Main C:\develop\woof\src\i_main.c:70
    #7 0x7ff794f1651f in main_getcmdline C:\develop\vcpkg\buildtrees\sdl2\src\ase-2.30.5-4439cd0809.clean\src\main\windows\SDL_windows_main.c:80
    #8 0x7ff794f1381b in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #9 0x7ff94f417373 in BaseThreadInitThunk+0x13 (C:\Windows\System32\KERNEL32.DLL+0x180017373)
    #10 0x7ff95101cc90 in RtlUserThreadStart+0x20 (C:\Windows\SYSTEM32\ntdll.dll+0x18004cc90)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: access-violation C:\develop\woof\src\mn_setup.c:3278 in MN_GetPixelWidth
==8612==ABORTING
```
</details>

### CODE REVIEW

File: src/mn_setup.c [hunk 1]
```diff
@@ -3830,16 +3830,16 @@ boolean MN_SetupResponder(menu_action_t action, int ch)
...
-    if ((current_item->m_flags & S_FUNC) && action == MENU_ENTER)
+    if ((current_item->m_flags & S_CALIBR) && action == MENU_ENTER)
     {
         if (ItemDisabled(current_item->m_flags))
         {
             M_StartSound(sfx_oof);
             return true;
         }
-        else if (current_item->var.func)
+        else
```
Comment (fabiangreffrath) [inline src/mn_setup.c:3840]: Do we need to check for `current_item->action` here?

Comment (rfomin) [reply src/mn_setup.c:3840]: No, because we only have one `S_CALIBR`, which always has `action`.

File: src/mn_internal.h [hunk 2]
```diff
@@ -102,7 +102,7 @@ void MN_DrawEnemy(void);
 #define S_HILITE      0x00000001 // Cursor is sitting on this item
 #define S_SELECT      0x00000002 // We're changing this item
 #define S_TITLE       0x00000004 // Title item
-#define S_FUNC        0x00000008 // Call var.func() on MENU_ENTER
+#define S_CALIBR      0x00000008 // Calibration item
```
Comment (ceski-1) [inline src/mn_internal.h:105]: Thanks for looking at this, but I had some future ideas for `S_FUNC`, that's why I kept it generalized.

Comment (rfomin) [reply src/mn_internal.h]: Okay, how about current version?

Comment (ceski-1) [reply src/mn_internal.h]: I think that's a good compromise and cleaner than what I had originally. I haven't tested with ASAN, so I'll go with your judgment.

**Review by ceski-1 — APPROVED** [review]
