### PR TITLE
fix use-button timer widget

### LINKED ISSUE #2204: Use-button time is recorded even if the widget is disabled
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/13346251593)._

If the use-button timer is enabled, the time of pressing the use button will be recorded even if the time widget is disabled, in which case the timer to show the use-button time won't be decremented. What this means is that I can press the use key while the time widget is disabled, and when I enable it, the use-button time will be shown regardless of how long ago the use button was pressed.

While we're here, maybe the use-button timer could be shown even if the rest of the time widget is disabled: it sounds somewhat reasonable for a speedrunner to want to see splits (i.e. the times when the use button is pressed) but not a constantly ticking timer which might be distracting.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
* decrease timer even if the widget is not visible
 * show use button timer widget even if level time widget is not visible

Fixes #2204

### CODE REVIEW

File: src/mn_setup.c [hunk 1]
```diff
@@ -1882,7 +1881,7 @@ static setup_menu_t stat_settings2[] = {
      .strings_id = str_show_widgets, .action = UpdateStatsFormatItem},
 
     {"Show Level Time", S_CHOICE, H_X, M_SPC, {"hud_level_time"},
-     .strings_id = str_show_widgets, .action = UpdateUseButtonItem},
```
Comment (fabiangreffrath) [inline src/mn_setup.c:1885]: I think if we allow to enable "Use-Button Timer" independent of "Show Level Time", we should move it back up into the "Widget Types" section.

Comment (ceski-1) [reply src/mn_setup.c:1885]: Sure. Something like "Show Use-Button Timer" would be consistent with the others.

How should this interact with the stats toggle key binding?

Comment (fabiangreffrath) [reply src/mn_setup.c:1885]: > Sure. Something like "Show Use-Button Timer" would be consistent with the others.

Yes, I will move it there.  

> How should this interact with the stats toggle key binding?

Not sure. Strictly, it's not one of the level stats widgets that are meant by this toggle. I'd leave it as it is. What do you think?

Comment (fabiangreffrath) [reply src/mn_setup.c:1885]: @MrAlaux you suggested to uncouple the use-button timer from the level time widget. What do you think?

Comment (ceski-1) [reply src/mn_setup.c:1885]: > I'd leave it as it is. What do you think?

That sounds fine to me.

Comment (MrAlaux) [reply src/mn_setup.c:1885]: > @MrAlaux you suggested to uncouple the use-button timer from the level time widget. What do you think?

Not quite _uncouple_, just make it independent but still existing within the same widget. Anyways, I agree on that it shouldn't be affected by the toggle key.
