### PR TITLE
fix garbage lines at the top of weapon sprites

### LINKED ISSUE #1371: Some sprites have a black outline
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7412300024)._

See the Fist:
woof0000

That's with _Triple_ resolution. _Original_, _Double_ and _High_ (which is 1364x640 in my case) are unaffected.

Do note that that's not the vanilla Fist sprite, but rather the one from this WAD: [DMSF_ALX-R3_FULL.zip](https://github.com/fabiangreffrath/woof/files/13839311/DMSF_ALX-R3_FULL.zip).
The vanilla sprite is unaffected. Not all other sprites from that WAD are affected either.

FWIW, this same issue is present in Nugget's 3X resolution.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1371

### CODE REVIEW

File: src/r_main.c [hunk 1]
```diff
@@ -510,6 +510,11 @@ void R_ExecuteSetViewSize (void)
   // psprite scales
   pspritescale = FixedDiv(viewwidth_nonwide, SCREENWIDTH);       // killough 11/98
   pspriteiscale= FixedDiv(SCREENWIDTH, viewwidth_nonwide);       // killough 11/98
+  // [FG] make sure that the product of the weapon sprite scale factor
+  //      and its reciprocal is always at least FRACUNIT to
+  //      fix garbage lines at the top of weapon sprites
+  while (FixedMul(pspriteiscale, pspritescale) < FRACUNIT)
+    pspriteiscale++;
```
Comment (rfomin) [inline src/r_main.c:517]: How about just `pspriteiscale = FixedDiv(SCREENWIDTH, viewwidth_nonwide) + 1;`, like in `V_Init()`.

Comment (fabiangreffrath) [reply src/r_main.c:517]: Not strictly necessary for even dividers, but alright for the sake of simplicity and consistency. 👍

**Review by rfomin — APPROVED** [review]
