### PR TITLE
do not override numerical values already set for MBF21 Bits fields

### LINKED ISSUE #236: Some MBF21 flags not working properly, also bad sfx error.
Using the 6.1.0 version, it seems that some of the MBF21 flags are still not supported. I have a melee weapon with the +SILENT flag, but still wakes up all monsters in a regular fashion, and a projectile that has the +RIP flag but does not pierce through enemies.

I'm also still getting a "bad sfx #:0" error. It seems to happen when I set Args3 to 0 for A_MonsterMeleeAttack (the arg that determines what sound is played on hit).

Provided is a DEHACKED that:
- adds +SILENT to the fist
- adds +RIP to the plasma projectile
- changes the Demon (Pinky) melee attack to A_MonsterMeleeAttack(20, 0 ,1)

[dehacked.txt](https://github.com/fabiangreffrath/woof/files/6762057/dehacked.txt)

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #236

@kraflab @XaserAcheron There is still a potential divide-by-zero crash if `damagemod` is set to `0` in either `A_MonsterBulletAttack()` or `A_MonsterMeleeAttack()`. How should we deal with this?

### CODE REVIEW

File: Source/p_enemy.c [hunk 1]
```diff
@@ -2905,7 +2905,8 @@ void A_MonsterMeleeAttack(mobj_t *actor)
   if (!P_CheckRange(actor, range))
     return;
 
-  S_StartSound(actor, hitsound);
+  if (hitsound > 0)
+    S_StartSound(actor, hitsound);
```
Comment (fabiangreffrath) [inline Source/p_enemy.c:2909]: We should probably just ignore `sfx_id == sfx_None` in `S_StartSound()`.

https://github.com/coelckers/prboom-plus/commit/06908671cb84e6b90d112c665b496fb493e21cc2

**Comment by kraflab** [comment]
If there are arg values that cause crashes we can catch those when parsing the dehacked file and do an I_Error I guess

**Comment by fabiangreffrath** [comment]
> If there are arg values that cause crashes we can catch those when parsing the dehacked file and do an I_Error I guess

On the other hand, there is currently no way to apply constant damage to a certain attack, e.g. if you want one bullet to exactly kill one certain kind of enemy. What if we catch the `damagemod == 0` case this way and apply `damagebase` as a constant value:

```
damage = (damagemod ? (P_Random(pr_mbf21) % damagemod + 1) : 1) * damagebase;
```

**Comment by XaserAcheron** [comment]
It's possible to do deal constant damage by setting `damagemod` to 1. I don't really have a strong preference on whether or not we do the same for `damagemod` = 0, or treat that as "zero damage", as long as it doesn't crash. :P

**Comment by kraflab** [comment]
Changing code pointer behaviour should be a last resort - let's treat this as an invalid value.

**Comment by fabiangreffrath** [comment]
> It's possible to do deal constant damage by setting `damagemod` to 1. 

Setting `damagemod` to `1` still involves calling `P_Random()` and takes its non-nodulated return value - this is not a constant.

> I don't really have a strong preference on whether or not we do the same for `damagemod` = 0, or treat that as "zero damage", as long as it doesn't crash. :P

"zero damage" is already achieved by setting `damagebase` to `0`.

> [EDIT] It's probably worth amending the MBF21 spec with whatever we decide here, so it's not ambiguous/undefined what happens in the zero case. The current spec doesn't consider zero an invalid value for this field, but it's kinda useless to set it and it's best to be explicit. :P

It is not undefined and not even useless - the game will crash. 😉

**Comment by fabiangreffrath** [comment]
>> Setting `damagemod` to `1` still involves calling `P_Random()` and takes its non-modulated return value - this is not a constant.

Nope, I'm wrong, sorry!

**Comment by XaserAcheron** [comment]
Sounds like a good reason to write up bounds-checking for args in general -- may as well also I_Error if you put in a negative value in any other `uint`-spec'd field, 'cause that be bad ;)

Still probably should update the spec to list the `damagemod` args as positive-int-only so other ports (have to) follow suit :P -- though what's a good common shorthand for a positive integer? Can't be `pint`, that means something else. 🍺

**Comment by kraflab** [comment]
I think just saying the word positive is fine :^)

**Comment by fabiangreffrath** [comment]
> I think just saying the word positive is fine :^)

I like the positivity of this. 😉 

How do we proceed? Should we introduce a check in the DEH parsing code or shall we just catch the div-by-zero in the respective functions right before it happens?

**Comment by kraflab** [comment]
I'd catch this in the parser. Dehacked implementation in the past is pretty "unfriendly" to modders because it lets you do things that crash and doesn't tell you why. Let's work on changing that 🤠

**Comment by fabiangreffrath** [comment]
Suggestion:
```patch
--- a/Source/d_deh.c
+++ b/Source/d_deh.c
@@ -3123,6 +3123,14 @@ void PostProcessDeh(void)
       for (; j >= 0; j--)
         if (!(defined_codeptr_args[i] & (1 << j)))
           states[i].args[j] = bexptr_match->default_args[j];
+
+      // ensure "damagemod" args are always positive to prevent division-by-zero
+      if ((bexptr_match->cptr == A_MonsterBulletAttack && states[i].args[4] <= 0) ||
+          (bexptr_match->cptr == A_MonsterMeleeAttack  && states[i].args[1] <= 0) ||
+          (bexptr_match->cptr == A_WeaponBulletAttack  && states[i].args[4] <= 0) ||
+          (bexptr_match->cptr == A_WeaponMeleeAttack   && states[i].args[1] <= 0))
+        I_Error("Action %s on state %d expects a positive \"damagemod\" arg. Check your dehacked.",
+          bexptr_match->lookup, i);
     }

     free(defined_codeptr_args);

```

**Comment by kraflab** [comment]
I'll think look into implementing generic validations. Maybe this kind of interface:

```c
for (i = 0; i < validation_count; ++i)
{
  validation_t v = bexptr_match->validations[i];
  switch (v.type)
  {
    case v_positive:
      if (args[v.arg] <= 0)
        I_Error(...);
    ...
  }
}
```
