### PR TITLE
reset set_tab_on on menu switching

### LINKED ISSUE #1427: Menu crash
Latest master with a clean config and using a debug build with ASAN enabled. Crashes after changing a few settings, then accessing the cosmetic weapons tab:

https://github.com/fabiangreffrath/woof/assets/56656010/8a28bd14-8179-4e5c-aef2-4432da663c83

[menu_asan.txt](https://github.com/fabiangreffrath/woof/files/14158422/menu_asan.txt)

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1427

### CODE REVIEW

File: src/m_menu.c [hunk 1]
```diff
@@ -2968,6 +2968,7 @@ static void M_KeyBindings(int choice)
   default_verify = false;
   setup_gather = false;
   mult_screens_index = M_GetMultScreenIndex(keys_settings);
+  set_tab_on = mult_screens_index;
```
Comment (fabiangreffrath) [inline src/m_menu.c:2971]: Is `set_tab_on` redundant with `mult_screens_index`?

Comment (rfomin) [reply src/m_menu.c:2971]: `set_tab_on` is the index of the tab the mouse cursor is on ("highlighted"), `mult_screens_index` changes when the tab is switched.

Yes, we currently have `setup_screens` and tabs which duplicate the same functionality, but I didn't want to touch old functions like `M_ResetDefault`/`M_InitDefaults` etc. We should simplify this in the future.

**Review by fabiangreffrath — APPROVED** [review]

**Review by ceski-1 — APPROVED** [review]
