### PR TITLE
fix DEH string mapping

### LINKED ISSUE #2663: Obituary-related crash
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/24708672896)._

This WAD ([direct download](https://robinsaviary.com/files/doomworld/plutatoes/PlutatoesE1-RC2.zip)) has custom enemies with custom obituaries; the game crashes if you die to one of them.

You can test this by starting a new game, enabling no-target mode, noclipping through the red-keyed door to your right until you find a translucent blue pinky, attacking it so that it attacks you, and letting it bite you to death.

I debugged this with GDB on a Nugget build based on the (almost) latest Woof master, and it had something to do with processing the obituary string.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
The previous code copied (parts of) a string to a pointer.

Fixes #2663

### CODE REVIEW

File: src/deh_mapping.c [hunk 1]
```diff
@@ -124,9 +124,9 @@ boolean DEH_SetStringMapping(deh_context_t *context, deh_mapping_t *mapping, voi
         return false;
     }
 
-    void *location = GetStructField(structptr, mapping, entry);
+    char **location = GetStructField(structptr, mapping, entry);
     // Copy value into field:
-    M_StringCopy(location, value, entry->size);
+    *location = M_StringDuplicate(value);
```
Comment (rfomin) [inline src/deh_mapping.c]: What if `*location` already points to an allocated memory buffer? For example, if there is a duplicate `Obituary` record by mistake.

Comment (fabiangreffrath) [reply src/deh_mapping.c]: Yes, right, this should be free()d before.

**Comment by rfomin** [comment]
I still think the string mapping code looks awkward. How about this patch (cosmetic):
```diff
diff --git a/src/deh_frame.c b/src/deh_frame.c
index fc3b16c1..ec29ca82 100644
--- a/src/deh_frame.c
+++ b/src/deh_frame.c
@@ -167,7 +167,7 @@ static void DEH_FrameParseLine(deh_context_t *context, char *line, int tag)
     }
 
     // set the appropriate field
-    DEH_SetMapping(context, &state_mapping, state, variable_name, ivalue);
+    DEH_SetMapping(context, &state_mapping, state, variable_name, ivalue, value);
 }
 
 static void DEH_FrameSHA1Sum(sha1_context_t *context)
diff --git a/src/deh_mapping.c b/src/deh_mapping.c
index bcfc836d..90352caf 100644
--- a/src/deh_mapping.c
+++ b/src/deh_mapping.c
@@ -57,11 +57,29 @@ static void *GetStructField(void *structptr, deh_mapping_t *mapping, deh_mapping
     return (uint8_t *)structptr + offset;
 }
 
+//
+// Set the value of a string field in a structure by name
+//
+
+static boolean SetStringMapping(deh_mapping_t *mapping, deh_mapping_entry_t *entry,
+                                void *structptr, char *name, char *value)
+{
+    char **location = GetStructField(structptr, mapping, entry);
+    // Copy value into field:
+    if (*location)
+    {
+        free(*location);
+    }
+    *location = M_StringDuplicate(value);
+    return true;
+}
+
 //
 // Set the value of a particular field in a structure by name
 //
 
-boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *structptr, char *name, int value)
+boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping,
+                       void *structptr, char *name, int ivalue, char *value)
 {
     deh_mapping_entry_t *entry = GetMappingEntryByName(context, mapping, name);
 
@@ -70,16 +88,14 @@ boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *str
         return false;
     }
 
-    // Sanity check:
     if (entry->is_string)
     {
-        DEH_Error(context, "Tried to set '%s' as integer (BUG)", name);
-        return false;
+        return SetStringMapping(mapping, entry, structptr, name, value);
     }
 
     if (entry->translate)
     {
-        value = entry->translate(value);
+        ivalue = entry->translate(ivalue);
     }
 
     void *location = GetStructField(structptr, mapping, entry);
@@ -90,13 +106,13 @@ boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *str
     switch (entry->size)
     {
         case 1:
-            *((uint8_t *)location) = value;
+            *((uint8_t *)location) = ivalue;
             break;
         case 2:
-            *((uint16_t *)location) = value;
+            *((uint16_t *)location) = ivalue;
             break;
         case 4:
-            *((uint32_t *)location) = value;
+            *((uint32_t *)location) = ivalue;
             break;
         default:
             DEH_Error(context, "Unknown field type for '%s' (BUG)", name);
@@ -106,35 +122,6 @@ boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *str
     return true;
 }
 
-//
-// Set the value of a string field in a structure by name
-//
-
-boolean DEH_SetStringMapping(deh_context_t *context, deh_mapping_t *mapping, void *structptr, char *name, char *value)
-{
-    deh_mapping_entry_t *entry = GetMappingEntryByName(context, mapping, name);
-    if (entry == NULL)
-    {
-        return false;
-    }
-
-    // Sanity check:
-    if (!entry->is_string)
-    {
-        DEH_Error(context, "Tried to set '%s' as string (BUG)", name);
-        return false;
-    }
-
-    char **location = GetStructField(structptr, mapping, entry);
-    // Copy value into field:
-    if (*location)
-    {
-        free(*location);
-    }
-    *location = M_StringDuplicate(value);
-    return true;
-}
-
 void DEH_StructSHA1Sum(sha1_context_t *context, deh_mapping_t *mapping, void *structptr)
 {
     // Go through each mapping
diff --git a/src/deh_mapping.h b/src/deh_mapping.h
index ee3fe9db..aa495b36 100644
--- a/src/deh_mapping.h
+++ b/src/deh_mapping.h
@@ -96,8 +96,8 @@ struct deh_mapping_s
     deh_mapping_entry_t entries[MAX_MAPPING_ENTRIES];
 };
 
-boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *structptr, char *name, int value);
-boolean DEH_SetStringMapping(deh_context_t *context, deh_mapping_t *mapping, void *structptr, char *name, char *value);
+boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping,
+                       void *structptr, char *name, int ivalue, char *value);
 void DEH_StructSHA1Sum(sha1_context_t *context, deh_mapping_t *mapping, void *structptr);
 
 #endif /* #ifndef DEH_MAPPING_H */
diff --git a/src/deh_sound.c b/src/deh_sound.c
index 3a7d16b1..5418a777 100644
--- a/src/deh_sound.c
+++ b/src/deh_sound.c
@@ -89,7 +89,7 @@ static void DEH_SoundParseLine(deh_context_t *context, char *line, int tag)
     int ivalue = atoi(value);
 
     // Set the field value
-    DEH_SetMapping(context, &sound_mapping, sfx, variable_name, ivalue);
+    DEH_SetMapping(context, &sound_mapping, sfx, variable_name, ivalue, value);
 }
 
 deh_section_t deh_section_sound =
diff --git a/src/deh_thing.c b/src/deh_thing.c
index 49a241b9..8b96c43e 100644
--- a/src/deh_thing.c
+++ b/src/deh_thing.c
@@ -321,20 +321,6 @@ static void DEH_ThingParseLine(deh_context_t *context, char *line, int tag)
             ivalue = PG_GROUPLESS;
         }
     }
-    else if (!strcasecmp(variable_name, "Obituary")
-            || !strcasecmp(variable_name, "Melee Obituary")
-            || !strcasecmp(variable_name, "Self Obituary"))
-    {
-        if (strlen(value) >= 1)
-        {
-            DEH_SetStringMapping(context, &thing_mapping, mobj, variable_name, value);
-        }
-        else
-        {
-            DEH_Warning(context, "%s is empty!", variable_name);
-        }
-        return;
-    }
     else if (!strcasecmp(variable_name, "Blood Color"))
     {
         deh_set_blood_color |= true;
@@ -345,7 +331,7 @@ static void DEH_ThingParseLine(deh_context_t *context, char *line, int tag)
     }
 
     // Set the field value
-    DEH_SetMapping(context, &thing_mapping, mobj, variable_name, ivalue);
+    DEH_SetMapping(context, &thing_mapping, mobj, variable_name, ivalue, value);
 }
 
 static void DEH_ThingSHA1Sum(sha1_context_t *context)
diff --git a/src/deh_weapon.c b/src/deh_weapon.c
index 838eb791..fd7ec4fe 100644
--- a/src/deh_weapon.c
+++ b/src/deh_weapon.c
@@ -125,7 +125,7 @@ static void DEH_WeaponParseLine(deh_context_t *context, char *line, int tag)
 
     // most values are integers
     int ivalue = atoi(value);
-    DEH_SetMapping(context, &weapon_mapping, weapon, variable_name, ivalue);
+    DEH_SetMapping(context, &weapon_mapping, weapon, variable_name, ivalue, value);
 }
 
 static void DEH_WeaponSHA1Sum(sha1_context_t *context)
```

**Comment by fabiangreffrath** [comment]
Sure, this looks clean!

**Comment by fabiangreffrath** [comment]
We should initialize the `size` field for string mappings with some dummy value here:

https://github.com/fabiangreffrath/woof/blob/18482a3abb77752fa803d2b6745838acc22f2d56/src/deh_mapping.h#L56-L59

**Comment by rfomin** [comment]
> We should initialize the `size` field for string mappings with some dummy value here:

Yes, perhaps with just `0`.

File: src/deh_mapping.c [hunk 2]
```diff
@@ -69,16 +88,14 @@ boolean DEH_SetMapping(deh_context_t *context, deh_mapping_t *mapping, void *str
         return false;
     }
 
-    // Sanity check:
```
Comment (fabiangreffrath) [inline src/deh_mapping.c:72]: Do we even need the `is_string` field here? We could just check if `value != NULL`.

Comment (rfomin) [reply src/deh_mapping.c:72]: I think `value` will always be non-NULL, it's a passed string, not converted to an integer.

File: src/deh_mapping.c [hunk 3]
```diff
@@ -57,11 +57,29 @@ static void *GetStructField(void *structptr, deh_mapping_t *mapping, deh_mapping
     return (uint8_t *)structptr + offset;
 }
 
+//
+// Set the value of a string field in a structure by name
+//
+
+static boolean SetStringMapping(deh_mapping_t *mapping, deh_mapping_entry_t *entry,
+                                void *structptr, char *name, char *value)
```
Comment (rfomin) [inline src/deh_mapping.c]: We don't need `char *name` parameter.

File: src/deh_mapping.c (hunk 2 above)
Comment (fabiangreffrath) [reply src/deh_mapping.c:72]: Yes, right. We read parameter `value` as string and then call `ivalue = atoi(value)`, so we can never know if `ivalue == 0` is an intentional setting or the result of a parsing error. We will need the extra information that a parameter is actually meant to be a string.

**Review by rfomin — APPROVED** [review]
Thank you!
